### ISSUE TITLE
Datasheet

### ISSUE THREAD

**Issue by lightelf76** [ilyakurdyukov/spreadtrum_flash#1]
Видел на хабре вашу статью. По ссылке есть даташит на чип, из интересного - в нем кроме ARM9 имеется еще микроконтроллер Cortex-M4, что может быть полезным дополнением для графики.
[https://datasheetspdf.com/pdf-file/1455703/Spreadtrum/SC6531E/1](url)

**Comment by ilyakurdyukov** [comment]
Написано что это для BlueTooth. Я уже использую память BlueTooth для стека.

Знаю про этот документ, посмотрите на версию 0.5, это утечка ранней версии документа, там не всё объясняется и этого не достаточно чтобы что-то запустить. Чтобы реально в каком-то устройстве на чипе разобраться - нужно много времени для исследования прошивки.
