### ISSUE TITLE
Can this tool reboot device to fastboot mode?

### ISSUE THREAD

**Issue by ArkYuki** [ilyakurdyukov/spreadtrum_flash#16]
My android tablet is kind of unusual. When powered off it can only boot to system (without any keys or with vol-), recovery (with vol +-) and sprd autoloader (with vol+). No fastboot.
I used to enter fastboot via adb but it was bricked due to some reasons. Can I use this tool to force reboot to fastboot mode?

**Comment by ilyakurdyukov** [comment]
I don't know if it's possible to force the reboot type via FDL.

**Comment by ArkYuki** [comment]
Ok I'll try later.
Just replace power_off with some other commands.

**Comment by ilyakurdyukov** [comment]
There is a command `BSL_CMD_NORMAL_RESET` that does a reset, but to normal mode. I don't know how to specify a different mode.

**Comment by ArkYuki** [comment]
it can't :(
