### ISSUE TITLE
Waiting for connection

### ISSUE THREAD

**Issue by Zesuga** [ilyakurdyukov/spreadtrum_flash#4]
Keep waiting and can't detect SPRD U2S Diag device in windows 11

**Comment by ilyakurdyukov** [comment]
This is not something I can help you with. It can be either:
- The device is not in boot mode.
- Windows refuses to use the [driver](https://github.com/libusb/libusb/wiki/Windows#driver-installation) for libusb.
- This is a completely different device than the ones I saw (incompatible with this boot interface).

**Comment by ilyakurdyukov** [comment]
You need to check that the USB device has the correct id: `1782:4d00`
Everything else is not the boot mode.
