### ISSUE TITLE
Hint: use OTG cable to force bootloader mode

### ISSUE THREAD

**Issue by ValdikSS** [ilyakurdyukov/spreadtrum_flash#7]
This is not an issue, just a hint, that you can force bootloader mode by using USB OTG cable (MicroUSB pin 5 is shorted to the ground).

I use USB-OTG adapter (USB-A female to MicroUSB), with USB-A-male to USB-A-male cable. It works much more reliable for 6531E than finding a boot key.

**Comment by ValdikSS** [comment]
Sorry, I haven't seen that it is already mentioned in the readme.

**Comment by ilyakurdyukov** [comment]
Also when purchasing OTG adapters, it is important to read reviews. I have seen people complain that the fifth pin in the adapter sold as OTG is not shorted.
